//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "app_user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub username: String,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub custom_username: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub email: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub wallet_address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub profile_picture_url: Option<String>,
    #[sea_orm(column_type = "Text", unique)]
    pub referral_code: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub referral_by: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub points: Decimal,
    pub email_verified: Option<bool>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub privacy_policy: bool,
    #[sea_orm(column_type = "Text")]
    pub policy_version: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub country: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_ip: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub betco_session_token: Option<String>,
    pub betco_player_id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub selected_token: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub selected_chain: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::betco_transaction_table::Entity")]
    BetcoTransactionTable,
    #[sea_orm(has_many = "super::cash_table::Entity")]
    CashTable,
    #[sea_orm(has_many = "super::coinflip_bet_cash::Entity")]
    CoinflipBetCash,
    #[sea_orm(has_many = "super::coinflip_bet_points::Entity")]
    CoinflipBetPoints,
    #[sea_orm(has_many = "super::crash_bets::Entity")]
    CrashBets,
    #[sea_orm(has_many = "super::crash_bets_cash::Entity")]
    CrashBetsCash,
    #[sea_orm(has_many = "super::dice_bet_cash::Entity")]
    DiceBetCash,
    #[sea_orm(has_many = "super::dice_bet_points::Entity")]
    DiceBetPoints,
    #[sea_orm(has_many = "super::flagged_users::Entity")]
    FlaggedUsers,
    #[sea_orm(has_many = "super::gas_donation::Entity")]
    GasDonation,
    #[sea_orm(has_many = "super::leaderboard::Entity")]
    Leaderboard,
    #[sea_orm(has_many = "super::limbo_bet_cash::Entity")]
    LimboBetCash,
    #[sea_orm(has_many = "super::limbo_bet_points::Entity")]
    LimboBetPoints,
    #[sea_orm(has_many = "super::point_table::Entity")]
    PointTable,
    #[sea_orm(has_many = "super::quests_submissions::Entity")]
    QuestsSubmissions,
    #[sea_orm(has_many = "super::quick_wags_submissions::Entity")]
    QuickWagsSubmissions,
    #[sea_orm(has_many = "super::raffle_round::Entity")]
    RaffleRound,
    #[sea_orm(has_many = "super::raffle_round_cash::Entity")]
    RaffleRoundCash,
    #[sea_orm(has_many = "super::raffle_ticket::Entity")]
    RaffleTicket,
    #[sea_orm(has_many = "super::raffle_ticket_cash::Entity")]
    RaffleTicketCash,
    #[sea_orm(has_many = "super::rake_back::Entity")]
    RakeBack,
    #[sea_orm(has_many = "super::rake_back_update::Entity")]
    RakeBackUpdate,
    #[sea_orm(has_many = "super::referral_balance::Entity")]
    ReferralBalance,
    #[sea_orm(has_many = "super::sbt_table::Entity")]
    SbtTable,
    #[sea_orm(has_many = "super::user_balance::Entity")]
    UserBalance,
    #[sea_orm(has_many = "super::user_connection::Entity")]
    UserConnection,
    #[sea_orm(has_many = "super::user_wallet::Entity")]
    UserWallet,
}

impl Related<super::betco_transaction_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BetcoTransactionTable.def()
    }
}

impl Related<super::cash_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CashTable.def()
    }
}

impl Related<super::coinflip_bet_cash::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoinflipBetCash.def()
    }
}

impl Related<super::coinflip_bet_points::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoinflipBetPoints.def()
    }
}

impl Related<super::crash_bets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrashBets.def()
    }
}

impl Related<super::crash_bets_cash::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrashBetsCash.def()
    }
}

impl Related<super::dice_bet_cash::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiceBetCash.def()
    }
}

impl Related<super::dice_bet_points::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiceBetPoints.def()
    }
}

impl Related<super::flagged_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FlaggedUsers.def()
    }
}

impl Related<super::gas_donation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GasDonation.def()
    }
}

impl Related<super::leaderboard::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Leaderboard.def()
    }
}

impl Related<super::limbo_bet_cash::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LimboBetCash.def()
    }
}

impl Related<super::limbo_bet_points::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LimboBetPoints.def()
    }
}

impl Related<super::point_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PointTable.def()
    }
}

impl Related<super::quests_submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuestsSubmissions.def()
    }
}

impl Related<super::quick_wags_submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuickWagsSubmissions.def()
    }
}

impl Related<super::raffle_round::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RaffleRound.def()
    }
}

impl Related<super::raffle_round_cash::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RaffleRoundCash.def()
    }
}

impl Related<super::raffle_ticket::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RaffleTicket.def()
    }
}

impl Related<super::raffle_ticket_cash::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RaffleTicketCash.def()
    }
}

impl Related<super::rake_back::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RakeBack.def()
    }
}

impl Related<super::rake_back_update::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RakeBackUpdate.def()
    }
}

impl Related<super::referral_balance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReferralBalance.def()
    }
}

impl Related<super::sbt_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SbtTable.def()
    }
}

impl Related<super::user_balance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserBalance.def()
    }
}

impl Related<super::user_connection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserConnection.def()
    }
}

impl Related<super::user_wallet::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserWallet.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
