//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "betco_transaction_table")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: Uuid,
    pub game_id: i32,
    pub player_id: i32,
    pub rgs_transaction_id: i64,
    #[sea_orm(column_type = "Decimal(Some((78, 18)))", nullable)]
    pub deposit_amount: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((78, 18)))", nullable)]
    pub withdraw_amount: Option<Decimal>,
    pub token: String,
    pub chain: String,
    pub is_rollback: bool,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app_user::Entity",
        from = "Column::UserId",
        to = "super::app_user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AppUser,
}

impl Related<super::app_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
