//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "casino_game_analytic")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub game: String,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub casino_earning: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub total_investment_overall: Decimal,
    pub max_player_count: i32,
    pub average_player_count: i32,
    pub total_player_count: i32,
    pub total_count: i32,
    pub total_count_today: i32,
    pub last_updated_date: Date,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
