//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dice_bet_cash")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub bet_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub cashout_multiplier: Decimal,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub cashout_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub profit_loss: Decimal,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))")]
    pub target: Decimal,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))")]
    pub result: Decimal,
    pub token: String,
    pub chain: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app_user::Entity",
        from = "Column::UserId",
        to = "super::app_user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AppUser,
}

impl Related<super::app_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
