//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "quick_wags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub title: String,
    pub r#type: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    pub points: Decimal,
    pub expired: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::quick_wags_submissions::Entity")]
    QuickWagsSubmissions,
}

impl Related<super::quick_wags_submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuickWagsSubmissions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
