//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "quick_wags_submissions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: Uuid,
    pub wags_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app_user::Entity",
        from = "Column::UserId",
        to = "super::app_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppUser,
    #[sea_orm(
        belongs_to = "super::quick_wags::Entity",
        from = "Column::WagsId",
        to = "super::quick_wags::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    QuickWags,
}

impl Related<super::app_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppUser.def()
    }
}

impl Related<super::quick_wags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuickWags.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
