//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rake_back")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: Uuid,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub total_deposit: Decimal,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub first_deposit: Decimal,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub second_deposit: Decimal,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub third_deposit: Decimal,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub fourth_deposit: Decimal,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub total_rake_back_amount: Decimal,
    pub count: i32,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub unlocked_rake_back: Decimal,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub claimed_rake_back: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app_user::Entity",
        from = "Column::UserId",
        to = "super::app_user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AppUser,
}

impl Related<super::app_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
