//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "referral_map")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub user_id: Uuid,
    pub username: String,
    pub level_type: String,
    pub referrer_a: Uuid,
    pub referrer_a_username: String,
    pub referrer_b: Option<Uuid>,
    #[sea_orm(column_type = "Decimal(Some((78, 18)))")]
    pub direct_cash_generated: Decimal,
    #[sea_orm(column_type = "Decimal(Some((78, 18)))")]
    pub indirect_cash_generated: Decimal,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app_user::Entity",
        from = "Column::ReferrerA",
        to = "super::app_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppUser2,
    #[sea_orm(
        belongs_to = "super::app_user::Entity",
        from = "Column::ReferrerB",
        to = "super::app_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppUser1,
}

impl ActiveModelBehavior for ActiveModel {}
