//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_connection_testnet")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub app_user_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub provider_user_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub email: Option<String>,
    pub email_verified: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub wallet_address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub username: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub picture_url: Option<String>,
    pub last_login_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub points: Decimal,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
