use actix_web::{HttpResponse, ResponseError, http::StatusCode};
use sea_orm::DbErr;
use serde::Serialize;
use thiserror::Error;
use r2d2_redis::r2d2::Error;

/// Custom Error type for the entire application
///
/// This enum centralizes all possible error condition that can occur
/// within the application, and converting them into well-defined HTTP
/// response for clients
///
/// It derives `Debug` for easy logging and `Error` for easy error message
/// generation
#[derive(Debug, Error)]
pub enum AppError {
    /// Represents an error related to application configuration.
    ///
    /// This could include missing env varibles, malformed config fiels or invalid
    /// settings at startup or runtime
    ///
    /// # Fields
    /// * `0` - A `String` detailing the specific config issue.
    #[error("Configuration Error: {0}")]
    ConfigError(String),

    /// Represents an error originating from the database layer (SeaORM)
    ///
    /// This variant automatically converts any SeaOrm db errors into AppError
    /// because of the `#[from]` attribute.
    ///
    /// # Fields
    /// * `0` - The underlying DbErr that occured.
    #[error("Database Error: {0}")]
    DbError(#[from] DbErr),

   #[error("Redis Error : {0}")]
   RedisErr(#[from] Error),

   #[error("Reqwest Error: {0}")]
   ReqwestError(#[from] reqwest::Error),

    // #[error("Authentication Error: {0}")]
    // AuthError(#[from] )
    /// Indicates that the requested resource could not be found.
    ///
    /// This error is typically returned when a client requests a resource
    /// that does not exist
    #[error("Not found")]
    NotFound,

    /// Represents a Bad request from client
    ///
    /// This error is returned when client doesnt request with the
    /// proper defined struct
    ///
    /// # Field
    /// * `0` - A `String` providing details about the request error
    #[error("Bad request: {0}")]
    BadRequest(String),

    /// Represents a unauthorized access of a client
    ///
    /// This error occurs when the client request some page or file
    /// without proper authenticating first.
    ///
    /// # Field
    /// * `0` - A `String` providing details about the unauthorized access
    #[error("Unauthorized: {0}")]
    Unauthorized(String),

    /// Represents a Forbidden access of a client
    ///
    /// This error occurs when the client request some page or file
    /// which they doesnt have access for
    ///
    /// # Field
    /// * `0` - A `String` providing details about the forbidden access
    #[error("Forbidden: {0}")]
    Forbidden(String),

    /// Represents a generic internal server error.
    ///
    /// This is used for unexpected errors that do not fit into
    /// any `AppError` vairants.
    ///
    /// # Fields
    /// * `0` - A `String` providing details about the internal error.
    #[error("Internal Server Error: {0}")]
    InternalError(String),

    /// Represents an unknown game identifier error.
    ///
    /// This error occurs when a game with the specified identifier 
    /// does not exist or is not recognized by the server.
    ///
    /// # Field
    /// * `0` - A `String` providing details about the unknown game.
    #[error("Unknow Game: {0}")]
    UnknownGame(String),


    /// Represents an error during a WebSocket operation.
    ///
    /// This error occurs when an issue is encountered while 
    /// handling a WebSocket connection or message.
    ///
    /// # Field
    /// * `0` - A `String` providing details about the WebSocket error.
    #[error("Webocker error:{0}")]
    WebsocketEror(String),
    
    #[error("Too many request error:{0}")]
    TooManyRequest(String),
}

/// Implements the `actix_web::ResponseError` trait for `AppError`.
///
/// This implementation allows `AppError` to be automatically converted into an
/// `actix_web::HttpResponse`, simplifying error handling in Actix-Web routes
/// by enabling the use of the `?` operator.
impl ResponseError for AppError {
    /// Converts the `AppError` into an `actix_web::HttpResponse`.
    ///
    /// This method constructs a JSON response containing the HTTP status code,
    /// a string representation of the status code (e.g., "Not Found"), and
    /// the detailed error message generated by `thiserror`.
    ///
    /// # Returns
    /// An `actix_web::HttpResponse` representing the error.
    fn error_response(&self) -> HttpResponse {
        let status_code = self.status_code();
        let error_message = self.to_string();

        /// A serializable struct used to format error responses consistently.
        ///
        /// This ensures that all error responses sent to the client adhere to a
        /// predefined JSON structure.
        #[derive(Serialize)]
        struct ErrorResponse {
            /// The HTTP status code (e.g., 404, 500).
            code: u16,
            /// A human-readable string representation of the HTTP status (e.g., "Not Found").
            error: String,
            /// The specific error message provided by the `AppError` variant.
            message: String,
        }

        HttpResponse::build(status_code).json(ErrorResponse {
            code: status_code.as_u16(),
            error: status_code.to_string(),
            message: error_message,
        })
    }

    /// Determines the appropriate `http::StatusCode` for each `AppError` variant.
    ///
    /// This method maps internal application errors to standard HTTP status codes,
    /// allowing clients to understand the nature of the error.
    ///
    /// # Returns
    /// An `actix_web::http::StatusCode` corresponding to the error.
    fn status_code(&self) -> StatusCode {
        match self {
            AppError::ConfigError(_) => StatusCode::INTERNAL_SERVER_ERROR,
            AppError::DbError(err) => match err {
                DbErr::Custom(msg) if msg.contains("No record found for key") => {
                    StatusCode::NOT_FOUND
                }
                _ => StatusCode::INTERNAL_SERVER_ERROR,
            },
            AppError::NotFound => StatusCode::NOT_FOUND,
            AppError::RedisErr(err)=> match err{
                _=>StatusCode::INTERNAL_SERVER_ERROR
            },
            AppError::ReqwestError(_) => StatusCode::INTERNAL_SERVER_ERROR,
            AppError::InternalError(_) => StatusCode::INTERNAL_SERVER_ERROR,
            AppError::BadRequest(_) => StatusCode::BAD_REQUEST,
            AppError::Unauthorized(_) => StatusCode::UNAUTHORIZED,
            AppError::Forbidden(_) => StatusCode::FORBIDDEN,
            AppError::UnknownGame(_) => StatusCode::NOT_FOUND,
            AppError::WebsocketEror(_) => StatusCode::BAD_REQUEST,
            AppError::TooManyRequest(_) => StatusCode::TOO_MANY_REQUESTS
        }
    }
}
